dist: xenial
language: node_js
node_js: "12"
cache: npm

before_install: cd client
install:
  - npm install -g yarn
  - yarn

script:
  - yarn lint
  - yarn build
  - yarn test -- --coverage --watchAll=false
  - yarn doc

branches:
  only:
  - master


