dist: xenial
language: node_js
node_js: "12"
cache: npm

before_install: 
  - cd client
  - npm install -g codecov
install:
  - npm install -g yarn
  - yarn

script:
  - yarn lint
  - yarn build
  - yarn test -- --coverage
  - yarn doc

branches:
  only:
  - master


